# This is a basic workflow to help you get started with Actions

name: Provision & Deploy PR to S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_if:
    if: github.event.issue.user.login == 'pfgray'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running S3 Deploy"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Runs a single command using the runners shell
      - name: Run yarn install
        run: |
          yarn install

      # Runs a set of commands using the runners shell
      - name: Run the build
        run: |
          yarn build

      - name: Create Bucket
        run: |
          aws s3api create-bucket --bucket ${{github.event.pull_request.number}}.paulgray.net
          aws s3api put-public-access-block --bucket "${{github.event.pull_request.number}}.paulgray.net" --public-access-block-configuration "BlockPublicPolicy=false"
          aws s3api put-bucket-policy --bucket "${{github.event.pull_request.number}}.paulgray.net" --policy '{
            "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "PublicReadGetObject",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": [
                    "s3:GetObject"
                  ],
                  "Resource": [
                    "arn:aws:s3:::'"${{github.event.pull_request.number}}.paulgray.net"'/*"
                  ]
                }
              ]
            }'

      - name: Deploy
        run: aws s3 sync ./public s3://${{github.event.pull_request.number}}.paulgray.net

      - name: Configure Website Hosting
        run: aws s3 website s3://${{github.event.pull_request.number}}.paulgray.net/ --index-document index.html --error-document 404.html

      - name: Configure DNS
        run: |
          aws route53 change-resource-record-sets --hosted-zone-id Z2P95MLRT2S18W --change-batch '
            {
              "Comment": "Alias record for S3 bucket",
              "Changes": [{
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "${{github.event.pull_request.number}}.paulgray.net",
                  "Type": "A",
                  "AliasTarget":{
                    "HostedZoneId": "Z3AQBSTGFYJSTF",
                    "DNSName": "s3-website-us-east-1.amazonaws.com",
                    "EvaluateTargetHealth": true
                  }
                }
              }]
            }
            ';

      - name: Find URL Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: A sample of this branch has been deployed at

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            :earth_americas: A sample of this branch has been deployed at http://${{github.event.pull_request.number}}.paulgray.net/
          edit-mode: replace
